CREATE TABLE `MATRIX_DATA` (
`MATRIX_ID` int DEFAULT NULL,
`ROW_NUM` int DEFAULT NULL,
`COL_NUM` int DEFAULT NULL,
`VALUE` decimal(10,5) DEFAULT NULL
) ;

CREATE TABLE `MATRIX` (
`MATRIX_ID` int DEFAULT NULL,
`ROW_DIM` int DEFAULT NULL,
`COL_DIM` int DEFAULT NULL
);